/bdd/test_coordinator:
  ros__parameters:
    event_topic: "/bdd/events"
    bhv_server_name: "/bdd/mockup_bhv_server"
    status_timer_period: 0.5
    use_sim_time: False
/bdd/mockup_behaviour:
  ros__parameters:
    event_topic: "/bdd/events"
    bhv_server_name: "/bdd/mockup_bhv_server"
    use_sim_time: False
    loop_duration: 0.01       # duration in seconds for step events
    heartbeat_duration: 0.35  # duration in seconds for callback
    delay_lower: 1.1          # lower range of duration for each state
    delay_upper: 1.7          # upper range of duration for each state
