/bdd_test/test_coordinator:
  ros__parameters:
    event_topic: "/bdd_test/events"
    use_sim_time: False
/bdd_test/mockup_behaviour:
  ros__parameters:
    event_topic: "/bdd_test/events"
    use_sim_time: False
    loop_duration: 0.01       # duration in seconds for step events
    heartbeat_duration: 0.04  # duration in seconds for callback
    delay_lower: 0.1          # duration in seconds for callback
    delay_upper: 0.15         # duration in seconds for callback
